export const referenceSources = {
  categories: { table: 'service_categories', select: 'id,name', order: 'sort_order' },
  blogCategories: { table: 'blog_categories', select: 'id,name', order: 'name' },
  providers: { table: 'providers', select: 'id,name', order: 'sort_order' },
};

export const resources = {
  Pages: {
    table: 'page_content', titleField: 'title', order: 'sort_order',
    select: 'id,slug,title,eyebrow,intro,body,seo_title,seo_description,status,sort_order,updated_at',
    fields: [
      ['title', 'Page title', 'text', true],
      ['slug', 'Page slug', 'text', true],
      ['eyebrow', 'Eyebrow label', 'text'],
      ['intro', 'Introduction', 'textarea'],
      ['body', 'Page content', 'textarea'],
      ['seo_title', 'SEO title', 'text'],
      ['seo_description', 'SEO description', 'textarea'],
      ['sort_order', 'Display order', 'number'],
      ['status', 'Status', 'select', true],
    ],
  },
  'Service Categories': {
    table: 'service_categories', titleField: 'name', order: 'sort_order',
    select: 'id,name,slug,description,hero_image_path,status,sort_order,seo_title,seo_description,updated_at',
    fields: [
      ['name', 'Category name', 'text', true],
      ['slug', 'URL slug', 'text', true],
      ['description', 'Category introduction', 'textarea'],
      ['hero_image_path', 'Category hero image', 'image', false, { bucket: 'service-images', maxMB: 5 }],
      ['seo_title', 'SEO title', 'text'],
      ['seo_description', 'SEO description', 'textarea'],
      ['sort_order', 'Display order', 'number'],
      ['status', 'Status', 'select', true],
    ],
  },
  Services: {
    table: 'services', titleField: 'name', order: 'sort_order',
    select: 'id,category_id,name,slug,short_description,description,benefits,price_label,duration_minutes,image_path,faq,status,sort_order,updated_at',
    fields: [
      ['category_id', 'Category', 'reference', true, { source: 'categories' }],
      ['name', 'Service name', 'text', true],
      ['slug', 'URL slug', 'text', true],
      ['short_description', 'Short description', 'textarea'],
      ['description', 'Full description', 'textarea'],
      ['benefits', 'Benefits (one per line)', 'list'],
      ['price_label', 'Price', 'text'],
      ['duration_minutes', 'Duration in minutes', 'number'],
      ['image_path', 'Service image', 'image', false, { bucket: 'service-images', maxMB: 5 }],
      ['faq', 'FAQs (one per line: Question | Answer)', 'faq'],
      ['sort_order', 'Display order', 'number'],
      ['status', 'Status', 'select', true],
    ],
  },
  Testimonials: {
    table: 'testimonials', titleField: 'client_name', order: 'sort_order',
    select: 'id,client_name,quote,rating,is_featured,status,sort_order,updated_at',
    fields: [
      ['client_name', 'Client display name', 'text', true],
      ['quote', 'Testimonial', 'textarea', true],
      ['rating', 'Rating (1-5)', 'number'],
      ['is_featured', 'Feature on homepage', 'checkbox'],
      ['sort_order', 'Display order', 'number'],
      ['status', 'Status', 'select', true],
    ],
  },
  Blog: {
    table: 'blog_posts', titleField: 'title', order: 'created_at', ascending: false,
    select: 'id,category_id,author_provider_id,title,slug,excerpt,body,featured_image_path,seo_title,seo_description,status,published_at,created_at,updated_at',
    fields: [
      ['title', 'Post title', 'text', true],
      ['slug', 'URL slug', 'text', true],
      ['category_id', 'Category', 'reference', false, { source: 'blogCategories' }],
      ['author_provider_id', 'Author', 'reference', false, { source: 'providers' }],
      ['excerpt', 'Excerpt (used on the listing page)', 'textarea'],
      ['body', 'Article content', 'textarea'],
      ['featured_image_path', 'Featured image', 'image', false, { bucket: 'blog-images', maxMB: 5 }],
      ['seo_title', 'SEO title', 'text'],
      ['seo_description', 'SEO description', 'textarea'],
      ['published_at', 'Publish date', 'datetime-local'],
      ['status', 'Status', 'select', true],
    ],
  },
  Promotions: {
    table: 'promotions', titleField: 'title', order: 'created_at', ascending: false,
    select: 'id,title,description,image_path,cta_label,cta_url,starts_at,ends_at,is_featured,status,created_at,updated_at',
    fields: [
      ['title', 'Promotion title', 'text', true],
      ['description', 'Description', 'textarea'],
      ['image_path', 'Promotion image', 'image', false, { bucket: 'promotion-images', maxMB: 5 }],
      ['cta_label', 'Button label', 'text'],
      ['cta_url', 'Button URL', 'url'],
      ['starts_at', 'Starts', 'datetime-local'],
      ['ends_at', 'Ends', 'datetime-local'],
      ['is_featured', 'Feature promotion', 'checkbox'],
      ['status', 'Status', 'select', true],
    ],
  },
  Announcements: {
    table: 'announcements', titleField: 'message', order: 'created_at', ascending: false,
    select: 'id,message,link_label,link_url,starts_at,ends_at,status,created_at,updated_at',
    fields: [
      ['message', 'Announcement message', 'textarea', true],
      ['link_label', 'Link label', 'text'],
      ['link_url', 'Link URL', 'url'],
      ['starts_at', 'Starts', 'datetime-local'],
      ['ends_at', 'Ends', 'datetime-local'],
      ['status', 'Status', 'select', true],
    ],
  },
  Provider: {
    table: 'providers', titleField: 'name', order: 'sort_order',
    select: 'id,name,credentials,title,slug,biography,philosophy,image_path,is_featured,status,sort_order,updated_at',
    fields: [
      ['name', 'Provider name', 'text', true],
      ['credentials', 'Credentials', 'text'],
      ['title', 'Professional title', 'text'],
      ['slug', 'URL slug', 'text', true],
      ['biography', 'Biography', 'textarea'],
      ['philosophy', 'Philosophy of care', 'textarea'],
      ['image_path', 'Provider portrait', 'image', false, { bucket: 'provider-images', maxMB: 5 }],
      ['is_featured', 'Featured provider', 'checkbox'],
      ['sort_order', 'Display order', 'number'],
      ['status', 'Status', 'select', true],
    ],
  },
};
export const statuses = ['draft', 'published', 'archived'];
